# Vector creation

In [1]:
import numpy as np
import time

In [2]:
# create a vector with four zero
a=np.zeros(4)
print(f"Vector: {a}  Datatype: {a.dtype} Shape: {a.shape}   ")
a=np.random.random_sample(4)
print(f"Vector: {a}  Datatype: {a.dtype} Shape: {a.shape}   ")
a=np.arange(10)
print(f"Vector: {a}  Datatype: {a.dtype} Shape: {a.shape}   ")
a=np.random.rand(4)
print(f"Vector: {a}  Datatype: {a.dtype} Shape: {a.shape}   ")
a=np.array([1,3,5,56,7,8,78])
print(f"Vector: {a}  Datatype: {a.dtype} Shape: {a.shape}   ")
a=np.array([2.3,4.5,6.7,8,123])
print(f"Vector: {a}  Datatype: {a.dtype} Shape: {a.shape}   ")

Vector: [0. 0. 0. 0.]  Datatype: float64 Shape: (4,)   
Vector: [0.65997729 0.85093583 0.22171912 0.12215173]  Datatype: float64 Shape: (4,)   
Vector: [0 1 2 3 4 5 6 7 8 9]  Datatype: int64 Shape: (10,)   
Vector: [0.14268337 0.94701559 0.0984109  0.46019603]  Datatype: float64 Shape: (4,)   
Vector: [ 1  3  5 56  7  8 78]  Datatype: int64 Shape: (7,)   
Vector: [  2.3   4.5   6.7   8.  123. ]  Datatype: float64 Shape: (5,)   


# Indexing

In [3]:
a=np.arange(10)
print(f"Vector is {a} and second element is {a[1]} and last element is {a[-1]} ")
try:
    c=a[20]
except Exception as e:
    print(f"The error message is {e} ")

Vector is [0 1 2 3 4 5 6 7 8 9] and second element is 1 and last element is 9 
The error message is index 20 is out of bounds for axis 0 with size 10 


# Slicing

In [4]:
a=np.arange(23)
print(f"Vector: {a}  ")
print(f"Slicing with one step increment: {a[2:15:1]} ")
print(f"Slicing with one step increment: {a[2:15:2]} ")
print(f"All elements before : {a[:7]}  ")
print(f"All elements after: {a[7:]}  ")
print(f"All the elements {a[:]} ")

Vector: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]  
Slicing with one step increment: [ 2  3  4  5  6  7  8  9 10 11 12 13 14] 
Slicing with one step increment: [ 2  4  6  8 10 12 14] 
All elements before : [0 1 2 3 4 5 6]  
All elements after: [ 7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]  
All the elements [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22] 


# Single vector operation

In [5]:
a=np.arange(10)
print(f"Vector {a} ")
print(f"Negate the vector {-a} ")
print(f"Sum of all elements {np.sum(a)}  ")
print(f"Mean of the vector {np.mean(a)}")
print(f"Square all the elements {a**2}  ")

Vector [0 1 2 3 4 5 6 7 8 9] 
Negate the vector [ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9] 
Sum of all elements 45  
Mean of the vector 4.5
Square all the elements [ 0  1  4  9 16 25 36 49 64 81]  


# Vector vector element wise operation

In [6]:
a=np.arange(5)
b=np.array([3,4,6,1,8])
print(f"{a} \n{b}\nSum of two array {a+b} ")

try:
    c=np.array([5,9])
    print(f"Sum of a and c: {a+c}  ")
except Exception as e:
    print(f"Error message: {e} ")


[0 1 2 3 4] 
[3 4 6 1 8]
Sum of two array [ 3  5  8  4 12] 
Error message: operands could not be broadcast together with shapes (5,) (2,)  


# Scalar vector operation

In [7]:
a=np.arange(10)
print(f"Vector:{a}\nMultiply vector with scalar: {5*a}  ")

Vector:[0 1 2 3 4 5 6 7 8 9]
Multiply vector with scalar: [ 0  5 10 15 20 25 30 35 40 45]  


# Dot product

In [8]:
# create function for dot product
def dot_product(a,b):
    m=a.shape[0]
    dot=0
    for i in range(m):
        dot+=a[i]*b[i]
    return dot

# find dot product using function
a=np.array([5,7])
b=np.array([2,3])
print(f"Dot product using my function {dot_product(a,b)}  ")

# Find dot product with build in function
print(f"Dot product using build in function {np.dot(a,b)}  ")

Dot product using my function 31  
Dot product using build in function 31  


# Need for speed: vector vs for loop

* vectorization provides a large speed 

In [9]:
a=np.random.rand(100000000)
b=np.random.rand(100000000)
tic=time.time()
result=dot_product(a,b)
toc=time.time()
print(f"Time taken by for loop:{toc-tic}  ")
tic=time.time()
result=np.dot(a,b)
toc=time.time()
print(f"Time taken by vector :{toc-tic}  ")
del(a)
del(b)

Time taken by for loop:33.04214668273926  
Time taken by vector :0.03823971748352051  


# Matrix

In [10]:
a=np.array([[2,3],[45,6]])
print(f"Matrix: \n{a} \nshape: {a.shape} ")

Matrix: 
[[ 2  3]
 [45  6]] 
shape: (2, 2) 


In [11]:
a=np.array((2,3))
print(f"Matrix: {a} shape: {a.shape} ")

Matrix: [2 3] shape: (2,) 


# Indexing

In [12]:
a=np.arange(10).reshape(-1,5)
print(f" Matrix: \n{a} ")

# access one element
print(f"Access one element {a[1][0]}  ")

# access one row
print(f"Access one row {a[1]} ")

# access one column
print(f"Access one column {a[:,2]} ")

 Matrix: 
[[0 1 2 3 4]
 [5 6 7 8 9]] 
Access one element 5  
Access one row [5 6 7 8 9] 
Access one column [2 7] 


# Slicing

In [13]:
a=np.arange(20).reshape(-1,4)
print(a)

# slice row and column - start:stop:step
print(a[:,1:3:1])
print(a[0:2:1,:])

# get all rows and column
print(a[:,:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [17 18]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
