# Numpy

# NumPy Arrays

## Key Points

### 1. Arrays are a Core Data Structure in NumPy
- Arrays are used to organize and store data efficiently.
- Think of an array as a grid of values.

### 2. All Elements Have the Same Data Type
- Every element in a NumPy array must be of the same type.
- Examples:
  - All integers
  - All floats
  - All strings

> Unlike Python lists, NumPy arrays cannot efficiently store mixed data types.

### 3. NumPy Arrays are Faster than Python Lists
- Operations are optimized internally.
- Calculations on large datasets run much faster.

### 4. NumPy Arrays Use Less Memory
- Arrays are stored in a compact format.
- More memory-efficient than Python lists.

### 5. NumPy Provides Many Built-in Functions
- Mathematical operations can be performed with very little code.
- Useful for:
  - Data analysis
  - Machine learning
  - Scientific computing

### 6. The Array Object is Called `ndarray`
- `ndarray` stands for **N-Dimensional Array**.
- Can represent:
  - 1-D arrays
  - 2-D arrays
  - 3-D arrays
  - Higher-dimensional arrays

### 7. 1-D Array
- Simplest NumPy array.
- Similar to a standard list of values.
- Stores data in a single dimension.


# Python List vs NumPy Array

| Feature | Python List | NumPy Array |
|----------|------------|-------------|
| Data Types | Mixed types allowed | Same type preferred |
| Speed | Slower | Faster |
| Memory Usage | More | Less |
| Mathematical Operations | Requires loops | Built-in support |
| Large Dataset Handling | Less efficient | Highly efficient |

---

# Why NumPy Arrays?

### Advantages
- Faster computations
- Lower memory usage
- Built-in mathematical operations
- Better performance on large datasets
- Supports multi-dimensional data
- No loop is required. NumPy performs the operation on all elements automatically.



In [ ]:
import numpy as np

In [ ]:
# Create one dimensional array
one_dimension=np.array([10,12])
print(one_dimension)
# other ways to create array
b=np.arange(5)
print(b)
# give start, end and increment value
c=np.arange(3,30,5)
print(c)
# create array with 5 elements that are evenly spaced
lin_spaced_array=np.linspace(1,100,5)
print(lin_spaced_array)
# above one gives array elements in float which is default
# we can change it to integer
lin_spaced_array=np.linspace(1,100,5,dtype=int)
print(lin_spaced_array)

# Change into float
c=np.arange(3,30,5,dtype=float)
print(c)

# find datatype of the array
char_array=np.array(["Hi I am learning how to code!"])
print(char_array)
print(char_array.dtype)

[10 12]
[0 1 2 3 4]
[ 3  8 13 18 23 28]
[  1.    25.75  50.5   75.25 100.  ]
[  1  25  50  75 100]
[ 3.  8. 13. 18. 23. 28.]
['Hi I am learning how to code!']
<U29


## U29 means
- U  = Unicode string(Can store text from any language and emojis)
- 29 = Maximum 29 characters

In [ ]:
one_array=np.ones(10)
print(one_array)
one_zero=np.zeros(10)
print(one_zero)
# Return a new array of shape 3, without initializing entries.
empty_array=np.empty(3)
print(empty_array)
# Return random values between 0 and 1
randome_array=np.random.rand(3)
print(randome_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[26.66666667 53.33333333 80.        ]
[0.88269559 0.05825904 0.10123682]


# Multi dimensional array

In [ ]:
two_dimensional_array=np.array([[1,2,3],[4,5,6]])
print(two_dimensional_array)
print("\n\n\n\n")
# Take one dimension and convert into two dimension
one_dimension=np.array([1,2,3,4,5,6,7,8,9,10])
two_dimensional_array=np.reshape(one_dimension,(5,2))
print(two_dimensional_array)

[[1 2 3]
 [4 5 6]]





[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


# Find size, shape and dimension of the array

In [ ]:
print(f"The dimension of the array is {two_dimensional_array.ndim}")
print(f"The shape of the array is {two_dimensional_array.shape}")
print(f"Number of elements in the array is {two_dimensional_array.size}")

The dimension of the array is 2
The shape of the array is (5, 2)
Number of elements in the array is 10


# Math operations

In [ ]:
arr_1=np.array([2,4,6])
arr_2=np.array([1,3,5])
print(f"array addition: {arr_1+arr_2}")
print(f"array subtraction: {arr_1-arr_2}")
print(f"Elementwise multiplication: {arr_1*arr_2}")

# Vector has miles covered by car and now you convert it to Km
# 1 mile=1.6 Km
miles=np.array([1,2,3,4,5])
print(f"The Kilometer covered are {miles*1.6}")


array addition: [ 3  7 11]
array subtraction: [1 1 1]
Elementwise multiplication: [ 2 12 30]
The Kilometer covered are [1.6 3.2 4.8 6.4 8. ]


# Indexing and slicing
- indexing to get specific element
- slicing to get a subset of elements

In [ ]:
#indexing element from one and two dimensional array
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[0])
b=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(b[0][4])

1
5


In [ ]:
#Slicing
print(a)
print(a[0:2])
print(a[:5])
print(a[4:])
print(a[::2])
print(two_dimensional_array)
print(two_dimensional_array[0:2]) # gives first two rows
print(two_dimensional_array[:,0]) # get the first column

[ 1  2  3  4  5  6  7  8  9 10]
[1 2]
[1 2 3 4 5]
[ 5  6  7  8  9 10]
[1 3 5 7 9]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[1 2]
 [3 4]]
[1 3 5 7 9]


# Stacking
- Join array in vertically or horizontally

In [ ]:
a=np.array([[1,1],[2,2]])
b=np.array([[3,3],[4,4]])
print(f"vertical stacking: \n {np.vstack((a,b))}")
print("\n")
print(f"Horizontal stacking: \n {np.hstack((a,b))}")

vertical stacking: 
 [[1 1]
 [2 2]
 [3 3]
 [4 4]]


Horizontal stacking: 
 [[1 1 3 3]
 [2 2 4 4]]


# LAB 2: Representing system of equations as matrix

In [15]:
import numpy as np
import matplotlib.pyplot as plt

# System of equation
- is a collection of more linear equation involving same variables
- A linear system is singular if it has no unique solution, and otherwise, it is said to be non-singular.
- equation can be represented as matrix, each row(equation), each column(coefficient)

Now represent this equation as matrix
$$
\begin{cases}
-x_1+3x_2=7, \\ 3x_1+2x_2=1, \end{cases}\tag{1}
$$

$$
\begin{bmatrix}
-1 & 3\\
3 & 2
\end{bmatrix}
$$

$$
\begin{bmatrix}
7 \\
1
\end{bmatrix}
$$


In [16]:
A=np.array([[-1,3],[3,2]],dtype=float)
b=np.array([7,1],dtype=float)
print(f"Matrix is :\n {A}")
print(f"\n Array is : {b}")

Matrix is :
 [[-1.  3.]
 [ 3.  2.]]

 Array is : [7. 1.]


In [17]:
# Find dimension of A and b
print(f"The dimension of Matrix A {A.shape}")
print(f"The dimension of Array b {b.shape}")


The dimension of Matrix A (2, 2)
The dimension of Array b (2,)


# Use np.linalg.solve(A,b) this function to solve the system of equations

In [18]:
x=np.linalg.solve(A,b)
print(f" The solution is {x}")

 The solution is [-1.  2.]


# Evaluate determinant of the matrix
- Square matrix where it has same number of rows and column, only on square matrix, we can find determinant
- use np.linalg.det(A)

In [11]:
d=np.linalg.det(A)
print(f"The determinant of the matrix A is {d:.2f}")

The determinant of the matrix A is -11.00


# Stack the matrix as below
$$
\begin{bmatrix}
-1 & 3 & 7 \\
3 & 2 & 1
\end{bmatrix}
$$

In [14]:
a_system=np.hstack((A,b.reshape(2,1)))
print(a_system)

# Take a row from this matrix
print(f"\n\nthe first row of this matrix {a_system[0]}")

[[-1.  3.  7.]
 [ 3.  2.  1.]]


the first row of this matrix [-1.  3.  7.]


# System of linear equation with no solution

$$
\begin{cases}
-x_1+3x_2=7, \\ 3x_1-9x_2=1, \end{cases}\tag{2}
$$

In [20]:
A=np.array([[-1,3],[3,-9]],dtype=float)
b=np.array([7,1])
print(f" The determinant of the matrix is {np.linalg.det(A)}")

 The determinant of the matrix is 0.0


In [21]:

try:
  solution=np.linalg.solve(A,b)
except np.linalg.LinAlgError as err:
  print(err)

Singular matrix


In [23]:
# Construct matrix corresponding to the linear equation
print(f" the corresponding matrix of this linear equation is \n {np.hstack((A,b.reshape(2,1)))}")

 the corresponding matrix of this linear equation is 
 [[-1.  3.  7.]
 [ 3. -9.  1.]]


# System of linear equation with infinite number of solutions

$$
\begin{cases}
-x_1+3x_2=7, \\ 3x_1-9x_2=-21, \end{cases}\tag{3}
$$

In [25]:
A=np.array([[-1,3],[3,-9]],dtype=float)
b=np.array([7,-21])

# Construct matrix corresponding to the system of equation
print(f"The corresponding matrix for the given system of equation \n {np.hstack((A,b.reshape(2,1)))}")

The corresponding matrix for the given system of equation 
 [[ -1.   3.   7.]
 [  3.  -9. -21.]]
