# Numpy
* python library used for array, matrix, vector and AI/Ml computation

# Vector
* one row or one column

In [4]:
# Create row and column vector

import numpy as np

row_vector =np.array([1,2,3])
print(row_vector)

column_vector=np.array([[1],[2],[3],[4]])
print(column_vector)

[1 2 3]
[[1]
 [2]
 [3]
 [4]]


# Matrix
* multiple row and column

In [5]:
matrix=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Creating a sparse matrix

* Example: each row is user and each column is movie, then matrix will have lots of zero
* Sparse matrix will store non zero element with position
* saves memory from storing 0



In [9]:
import numpy as np
from scipy import sparse
matrix=np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# create compressed sparse row matrix
sparse_matrix=sparse.csr_matrix(matrix)
print(sparse_matrix)

<Compressed Sparse Row sparse matrix of dtype 'int32'
	with 2 stored elements and shape (3, 10)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


# Selecting elements in a matrix/array

In [21]:
import numpy as np

vector=np.array([1,2,3,4,6,7,8,9,0])
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])


# select one element from vector/matrix
print(vector[0])
print(matrix[0,2])

# select all elements from vector
print(vector[:])

# select with range
print(vector[:2])

# select last element
print(vector[-1])

# select first 2 rows with all column_vector
print(matrix[:2,:])


#select all row and second column_vector
print("------")
print(matrix[:,1])# dimension reduced
print(matrix[:,1:2]) # : --> dimensions preserved

1
3
[1 2 3 4 6 7 8 9 0]
[1 2]
0
[[1 2 3]
 [4 5 6]]
------
[2 5 8]
[[2]
 [5]
 [8]]
