# Numpy tutorial

https://www.youtube.com/watch?v=1qz7qUM6yUI&list=PLxJrBqNOQsPI8HVh1eorkOCjVjCJ2dQic

# Comparing Numpy and Python List


# Multiply the list of number with 2 and then repeat it for 10,000 times
* NumPy is faster than Python lists
* NumPy uses less memory than lists
* NumPy has many built-in mathematical and scientific functions
* NumPy arrays usually contain only one datatype, while Python lists can contain different datatypes
* can do direct operation instead of having for loop
  

In [9]:
import numpy as np
import time
# List
a=[1,2,3,4,5,6,7,8,9,0]*10000000
start= time.time() # time.time() returns the current time in seconds
for i in range(len(a)):
    a[i]=a[i]*2
print("Time taken for list " + str(time.time() - start))


# numpy
a=[1,2,3,4,5,6,7,8,9,0]*10000000
b=np.array(a)
start=time.time()
b=b*2
print("time take for numpy " + str(time.time() - start))

Time taken for list 10.336825609207153
time take for numpy 0.22186613082885742


*  

In [20]:
import numpy as np # np is %alias
arr=np.array([1,2,3]) # creates numpy array


In [21]:
# dimension 
arr.ndim  # one dimension for array

arr=np.array(234)
arr.ndim # zero dimension for scalar

0

In [22]:
a=np.array([])
a.ndim # one bracket one dimension

1

In [24]:
b=np.array([[]])
b.ndim # two dimension
b.shape

(1, 0)

In [26]:
range=np.arange(0,20) # create array by mentioning range of the value , default step count is 1
range


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
# Change the step count
range=np.arange(0,20,2) #start value, stop value, step count
range

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
arr=np.linspace(0,1,5) # value range between 0 and 1 and it should have 5 values which will be eventually spaced
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [31]:
arr=np.linspace(0,1,10) # now 10 values
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [33]:
arr=np.zeros(10) # one dimensional array with zero
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
arr=np.zeros([10,2]) # zero matrix
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [37]:
arr=np.ones(20)# create array with 1
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [40]:
arr=np.ones([10,8],dtype=int) # if we dont give dtype, it will take float as default
arr

array([['1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1']], dtype='<U1')

In [44]:
arr=np.full(10,20) # create array with value 20
arr

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [46]:
arr=np.full([10,7],66) # create matrix with 66 value
arr

array([[66, 66, 66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66, 66, 66]])

In [52]:
np.random.rand() # create random float from 0 to 1

print(np.random.rand(3)) # get 3 random values
print(np.random.rand(10,3)) # get 10 by 3 matrix with random values

[0.90883936 0.45115032 0.22514716]
[[0.91136302 0.34402665 0.35915408]
 [0.00713571 0.92890134 0.68120105]
 [0.17347649 0.74164633 0.60522797]
 [0.53102054 0.93801629 0.9693477 ]
 [0.35754513 0.97017254 0.86671939]
 [0.28913411 0.46271542 0.5781597 ]
 [0.12088198 0.40668085 0.32777199]
 [0.16119791 0.89890939 0.58671253]
 [0.23401642 0.82599971 0.46224218]
 [0.58345341 0.59772268 0.84829568]]


In [55]:
arr=np.random.randn(10,4) # random float from standard normal distribution where mean 0 and standard deviation 1
arr

array([[ 1.08025926,  0.80652791, -0.1278676 , -0.93447982],
       [ 0.14646704, -1.83245921, -0.18047761, -1.09488892],
       [-1.0508365 ,  0.10632024,  0.67163518,  1.28923622],
       [ 0.22793653, -0.09484868, -1.53890222, -1.6528227 ],
       [ 1.08506436,  1.5081784 , -0.35165793, -1.72378205],
       [ 1.36110775, -0.74787128,  0.51801873,  0.37919636],
       [-0.42438097, -0.20445376, -0.81920724, -0.52061271],
       [-0.54507228, -0.19829719, -0.13041049,  0.73815771],
       [-0.97512476,  0.82255392,  1.14463894,  0.94144594],
       [ 0.08275935, -0.60814014,  1.05407073,  0.05020237]])

In [57]:
arr=np.random.randint(10,100,size=(10,6)) # get random integer , here mention start, stop value and size
arr

array([[81, 49, 99, 31, 82, 32],
       [26, 91, 57, 14, 96, 86],
       [89, 82, 84, 85, 81, 32],
       [51, 87, 22, 45, 92, 29],
       [26, 19, 40, 78, 35, 61],
       [47, 70, 16, 79, 91, 88],
       [27, 58, 74, 97, 30, 74],
       [82, 15, 10, 50, 67, 58],
       [72, 38, 42, 89, 29, 50],
       [38, 29, 12, 53, 36, 16]], dtype=int32)

# Numpy Data type and type Casting

In [59]:
arr=np.array([1,2,3,4,56,76,78,78,787,314,432]) # creating numpy array manually
arr


array([  1,   2,   3,   4,  56,  76,  78,  78, 787, 314, 432])

In [1]:
# if we change even one element datatype, every element datatype changes
import numpy as np
arr=np.array([1,2,3.4,4,56,76,78,78,787,314,432]) 
print(arr)

arr=np.array([1,'34',2,3.4,4,56,76,78,78,787,314,432]) 
print(arr)
print(type(arr))

[  1.    2.    3.4   4.   56.   76.   78.   78.  787.  314.  432. ]
['1' '34' '2' '3.4' '4' '56' '76' '78' '78' '787' '314' '432']
<class 'numpy.ndarray'>


In [2]:
list=['string',0,3.5] # creating a list and then converting list to numpy array
arr=np.array(list) # here all elements are getting converted into string
arr

array(['string', '0', '3.5'], dtype='<U32')

* int 32 32 bit integer can store smaller integer value
* int64 64 bit integer can store larger integer number
* float 32
* float 64
* bool Ture or flase
* complex
* str 


In [3]:
arr=np.array([1,2,3,4,5]) # created integer array
arr.dtype

dtype('int64')

In [5]:
arr=np.array([2.3,45.5]) # create float array
arr.dtype

dtype('float64')

In [7]:
arr=np.array(['leka','dakshinamurthy',2.3,45.5])
arr.dtype


dtype('<U32')

In [10]:
arr=np.array([1,2,4,45,6],dtype=float)
arr.dtype


array([ 1.,  2.,  4., 45.,  6.])