# Tensors: The Core of PyTorch

# 1. Tensor Creation

In PyTorch, data must be converted into **tensors** before it can be used by a model.

## 1.1 From Existing Data Structures

Tensors can be created from existing data such as:

- Python lists
- NumPy arrays
- Pandas DataFrames


In [1]:
import torch
import numpy as np
import pandas as pd

In [2]:
list = [1, 2, 3]                 # Python list
list_tensor = torch.tensor(list) # Convert list → tensor
print(f"Tensor datatype: {list_tensor.dtype}")

numpy_array=np.array([[1,2,3],[4,5,6],[7,8,9]]) # Numpy array
numpy_array_tensor=torch.from_numpy(numpy_array) # convert numpy array → tensor
print("Tensor from numpy array: \n",numpy_array_tensor)


Tensor datatype: torch.int64
Tensor from numpy array: 
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


## Converting a Pandas DataFrame to a Tensor

- **Pandas DataFrame** stores tabular data in **rows and columns**.
- Commonly used to load datasets from **CSV files**.
- There is no direct DataFrame → Tensor conversion.
- First convert **DataFrame → NumPy array** using `.values`.
- Then convert **NumPy array → Tensor** using `torch.tensor()`.

```python
tensor = torch.tensor(df.values)

In [3]:
df = pd.read_csv('./data.csv')   # CSV → DataFrame

all_values = df.values           # DataFrame → NumPy array

dataframe_tensor = torch.from_numpy(all_values)  # NumPy → Tensor

print(f"Dataframe: {df} \nDataframe to Tensor: {dataframe_tensor}")

Dataframe:    distance_miles  delivery_time_minutes
0            1.60                   7.22
1           13.09                  32.41
2            6.97                  17.47 
Dataframe to Tensor: tensor([[ 1.6000,  7.2200],
        [13.0900, 32.4100],
        [ 6.9700, 17.4700]], dtype=torch.float64)


### 1.2 - With Predefined Values

In [4]:
# All zero
zero=torch.zeros(2,3)
print(f"Tensor with zeros:\n {zero} \n\n")

# All ones
one=torch.ones(2,3)
print(f"Tensor with ones:\n {one} ")

# random number between 0 and 1
random=torch.rand(2,3)
print(f"\n\nRandom Tensor:\n {random} ")

Tensor with zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 


Tensor with ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 


Random Tensor:
 tensor([[0.2870, 0.3443, 0.7057],
        [0.9014, 0.9078, 0.5964]]) 


## 1.3 From a Sequence

`torch.arange()` creates a **1D tensor containing a sequence of numbers**.

### Syntax

```python
torch.arange(start, stop, step)

In [5]:
range_tensor=torch.arange(10,100,10)
print(f"Range tensor: {range_tensor} ")

Range tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90]) 


# 2. Reshaping & Manipulating Tensors

Tensor **shape** must match the shape expected by the model.

- Shape mismatch is a common source of PyTorch errors.
- Models usually process data in **batches**.
- Even a single sample may need to be represented as a **batch of 1**.

## 2.1 Checking Tensor Dimensions

Use `.shape` to check the dimensions of a tensor.

```python
tensor.shape

In [6]:
x=torch.tensor([[1,2,3],[4,5,6]])
print(f"Shape of tensor: {x.shape} ")

Shape of tensor: torch.Size([2, 3]) 


## 2.2 - Changing a Tensor's Dimensions

### `unsqueeze()` — Add a Dimension

`unsqueeze(dim)` adds a new dimension of size `1` at the specified position.

`squeeze()` removes dimensions that have a size of `1`.


In [7]:
print(f"Shape of tensor: {x.shape} ")
expanded=x.unsqueeze(0)
print(f"Shape after unsqueeze is {expanded.shape} ")
print("\n\n\n", expanded)

Shape of tensor: torch.Size([2, 3]) 
Shape after unsqueeze is torch.Size([1, 2, 3]) 



 tensor([[[1, 2, 3],
         [4, 5, 6]]])


In [8]:
print(f"Shape after unsqueeze is {expanded.shape} ")
print("\n\n\n", expanded)
squeezed=expanded.squeeze()
print(f"Shape after squeeze is {squeezed.shape} ")
print("\n\n\n",squeezed)

Shape after unsqueeze is torch.Size([1, 2, 3]) 



 tensor([[[1, 2, 3],
         [4, 5, 6]]])
Shape after squeeze is torch.Size([2, 3]) 



 tensor([[1, 2, 3],
        [4, 5, 6]])


### 2.3 - Restructuring


* **Reshaping:** `torch.Tensor.reshape()` changes the shape of a tensor to the specified dimensions.

In [9]:
x=torch.tensor([[1,2,3,4],[5,6,7,8]])
print(f"Original tensor: \n{x} \n\n Shape: {x.shape} ")
print("-"*70)
reshaped_tensor=x.reshape(4,2)
print(f"Reshaped tensor: \n{reshaped_tensor}\n\nShape: {reshaped_tensor.shape} ")

Original tensor: 
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]]) 

 Shape: torch.Size([2, 4]) 
----------------------------------------------------------------------
Reshaped tensor: 
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

Shape: torch.Size([4, 2]) 


* **Transposing:** `torch.Tensor.transpose()` swaps the specified dimensions of a tensor.

In [10]:
print(f"Original tensor: \n\n{x}\nShape: {x.shape} ")
print("-"*70)
transposed=x.transpose(0,1)
print(f"Tranposed tensor: \n\n{transposed}\nShape: {transposed.shape} ")


Original tensor: 

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
Shape: torch.Size([2, 4]) 
----------------------------------------------------------------------
Tranposed tensor: 

tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])
Shape: torch.Size([4, 2]) 


### 2.4 - Combining Tensors

In the data preparation stage, we might need to combine data from different sources or merge separate batches into one larger dataset.

* `torch.cat()`: Joins a sequence of tensors along an existing dimension. Note: All tensors must have the same shape in dimensions other than the one being concatenated.

In [19]:
# Concatenate along Row
a=torch.tensor(
    [[1, 2, 3],
     [4, 5, 6]])
b=torch.tensor(
    [[7, 8, 9],
     [10,11,12]])
con=torch.cat((a,b),dim=0)
print(f'Concatenated along row: \n {con} ')
print("-"*70)

# Concatenate along column
con=torch.cat((a,b),dim=1)
print(f"\n\nConcatenated along column: \n{con} ")

Concatenated along row: 
 tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]) 
----------------------------------------------------------------------


Concatenated along column: 
tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]]) 


## 3 - Indexing & Slicing

After you have your data in a tensor, you will often need to access specific parts of it. Whether you are grabbing a single prediction to inspect its value, separating your input features from your labels, or selecting a subset of data for analysis, indexing and slicing are the tools for the job.

### 3.1 - Accessing Elements

These are the fundamental techniques for getting data out of a tensor, working very similarly to how you would access elements in a standard Python list.

* **Standard Indexing**: Accessing single elements or entire rows using integer indices (e.g., `x[0]`, `x[1, 2]`).

In [26]:
# Create tensor
x=torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]])

print(f"Original tensor:\n{x} ")
print("-"*70)
print(f"\n Accessing single element: {x[0][0]} ")
print("-"*70)
print(f"Accessing second row: {x[1]} ")
print("-"*70)
print(f"Accessing last row: {x[-1]} ")

Original tensor:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]) 
----------------------------------------------------------------------

 Accessing single element: 1 
----------------------------------------------------------------------
Accessing second row: tensor([5, 6, 7, 8]) 
----------------------------------------------------------------------
Accessing last row: tensor([ 9, 10, 11, 12]) 


<br>

* **Slicing**: Extracting sub-tensors using `[start:end:step]` notation (e.g., `x[:2, ::2]`).
    * *Note: The `end` index itself is not included in the slice.*
* Slicing can be used to access entire columns.

In [34]:
x=torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]])

print(f"Original tensor:\n{x} ")
print('-'*70)
print(f"\nFirst two rows \n: {x[0:2]} ")
print('-'*70)
print(f"\nThird coloumn: \n {x[:,2]} ")
print(f"\nEvery other column\n: {x[:,::2]} ")
print(f"Last column: \n {x[:,-1]} ")

Original tensor:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]) 
----------------------------------------------------------------------

First two rows 
: tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]]) 
----------------------------------------------------------------------

Third coloumn: 
 tensor([ 3,  7, 11]) 

Every other column
: tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11]]) 
Last column: 
 tensor([ 4,  8, 12]) 


* Combining Indexing & Slicing

In [35]:
x=torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]])

print(f"Original tensor:\n{x} ")
print('-'*70)
print(f"First two row and last two column: \n {x[0:2,2:]} ")

Original tensor:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]) 
----------------------------------------------------------------------
First two row and last two column: 
 tensor([[3, 4],
        [7, 8]]) 


<br>

* **`.item()`**: Extracts the value from a single-element tensor as a standard Python number.

In [43]:
x=torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]])
single_element=x[2][1]
print(f"Single element: {single_element} ")
# convert tensor to python number
python_number=single_element.item()
print(f"Tensor number is converted into python number {python_number} and its datatype is {type(python_number)} ")

Single element: 10 
Tensor number is converted into python number: 10 and its datatype is <class 'int'> 
