# Tensors: The Core of PyTorch
# 1. Tensor Creation

In PyTorch, data must be converted into **tensors** before it can be used by a model.

## 1.1 From Existing Data Structures

Tensors can be created from existing data such as:

- Python lists
- NumPy arrays
- Pandas DataFrames


In [1]:
import pandas as pd
import torch
import numpy as np


In [2]:
# list is converted to tensor
my_list=[1,2,3,4,5,6]
list_tensor=torch.tensor(my_list)
print(f"List is converted to tensor:\n {list_tensor} \n")
print('-'*70)

# Array is converted to tensor
array=np.array([[1,2,3,4],[5,6,7,8]])
array_tensor=torch.from_numpy(array)
print(f"Array is converted to tensor: \n{array_tensor} ")
print('-'*70)

# datafram is converted to array and then converted to tensor
dataframe=pd.read_csv('./data.csv')
dataframe_array=dataframe.values
dataframe_array_tensor=torch.from_numpy(dataframe_array)
print(f"\nDataframe is converted into tensor: \n{dataframe_array_tensor} ")
print('-'*70)

List is converted to tensor:
 tensor([1, 2, 3, 4, 5, 6]) 

----------------------------------------------------------------------
Array is converted to tensor: 
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]]) 
----------------------------------------------------------------------

Dataframe is converted into tensor: 
tensor([[ 1.6000,  7.2200],
        [13.0900, 32.4100],
        [ 6.9700, 17.4700]], dtype=torch.float64) 
----------------------------------------------------------------------


### 1.2 - With Predefined Values

Sometimes we need to create tensors for specific purposes, like initializing a model's weights and biases before training begins. PyTorch allows you to quickly generate tensors filled with placeholder values like zeros, ones, or random numbers, which is useful for testing and setup.

* `torch.zeros()`: Creates a tensor filled with zeros of the specified dimensions.

* `torch.ones()`: Creates a tensor filled with ones of the specified dimensions.

* `torch.rand()`: Generates a tensor with random numbers uniformly distributed between 0 and 1, based on the specified dimensions.



In [3]:
# All zero
zero_tensor=torch.zeros(2,3)
print(f"Zero Tensor:\n {zero_tensor} \n")
print('-'*70)

# All one
one_tensor=torch.ones(2,3)
print(f'One tensor: \n{one_tensor} \n')
print('-'*70)

# Random value between 0 and 1
random_tensor=torch.rand(2,3)
print(f"Random Tensor:\n{random_tensor} \n")
print('-'*70)

Zero Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

----------------------------------------------------------------------
One tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

----------------------------------------------------------------------
Random Tensor:
tensor([[0.9771, 0.8033, 0.4320],
        [0.4096, 0.6880, 0.0273]]) 

----------------------------------------------------------------------


* ### 1.3 - From a Sequence

For situations where we need to generate a sequence of data points, such as a range of values for testing a model's predictions, we can create a tensor directly from that sequence.

* `torch.arange()`: Creates a 1D tensor containing a range of numbers from the specified start value to one less than the specified stop value, incrementing (if positive) or decrementing (if negative) by the specified `step` value.

In [4]:
# Range of values in tensor
range_tensor=torch.arange(10,50,step=4)
print(f"Range of values in Tensor: \n {range_tensor} ")

Range of values in Tensor: 
 tensor([10, 14, 18, 22, 26, 30, 34, 38, 42, 46]) 


## 2 - Reshaping & Manipulating

A very common source of errors in PyTorch projects is a mismatch between the shape of your input data and the shape your model expects. For instance, a model is typically designed to process a batch of data, so even if you want to make a single prediction, you must shape your input tensor to look like a batch of one. Mastering tensor reshaping is a key step toward building and debugging models effectively.

### 2.1 - Checking a Tensor's Dimensions

The first step to fixing a shape mismatch is to understand the current dimensions of your tensor. Checking the shape is your primary debugging tool. It tells you how many samples you have and how many features are in each sample.

* `torch.Tensor.shape`: An attribute that returns a `torch.Size` object detailing the size of the tensor along each dimension.

In [5]:
x=torch.tensor([[1,2,3,5],[4,5,6,9]])
print(f"Original tensor: \n {x} ")
print(f"\nTensor Shape: {x.shape} ")

Original tensor: 
 tensor([[1, 2, 3, 5],
        [4, 5, 6, 9]]) 

Tensor Shape: torch.Size([2, 4]) 


### 2.2 - Changing a Tensor's Dimensions

Once you identify a shape mismatch, you need to correct it. A frequent task is adding a dimension to a single data sample to create a batch of size one for your model, or removing a dimension after a batch operation is complete.

* **Adding Dimension:** `torch.Tensor.unsqueeze()` inserts a new dimension at the specified index.
    * *Notice how the shape will change from `[2, 3]` to `[1, 2, 3]` and the tensor gets wrapped in an extra pair of square brackets `[]`*.

In [6]:
x=torch.tensor([1,2,3,4])
print(f"Original tensor: \n {x}\n Tensor Shape: {x.shape}\n{'-'*70}\n ")

expanded=x.unsqueeze(0)
print(f"Tensor after unsqueeze {expanded} \nShape of tensor after unsqueeze: {expanded.shape} ")

Original tensor: 
 tensor([1, 2, 3, 4])
 Tensor Shape: torch.Size([4])
----------------------------------------------------------------------
 
Tensor after unsqueeze tensor([[1, 2, 3, 4]]) 
Shape of tensor after unsqueeze: torch.Size([1, 4]) 


<br>

* **Removing Dimension:** `torch.Tensor.squeeze()` removes dimensions of size 1.
    * *This reverses the unsqueeze operation, removing the `1` from the shape and taking away a pair of outer square brackets*.

In [7]:

print(f"Expanded tensor: \n {expanded}\n Tensor Shape: {expanded.shape} \n{'-'*70}\n ")

after_squeeze=expanded.squeeze()
print(f"Tensor after squeeze \n {after_squeeze}\n Shape: {after_squeeze.shape} ")

Expanded tensor: 
 tensor([[1, 2, 3, 4]])
 Tensor Shape: torch.Size([1, 4]) 
----------------------------------------------------------------------
 
Tensor after squeeze 
 tensor([1, 2, 3, 4])
 Shape: torch.Size([4]) 


### 2.3 - Restructuring

Beyond just adding or removing dimensions, you may need to completely change a tensor's structure to match the requirements of a specific layer or operation within your neural network.

* **Reshaping:** `torch.Tensor.reshape()` changes the shape of a tensor to the specified dimensions.

In [8]:
x=torch.tensor([[1,2,3,5],[4,5,6,9]])
print(f"Original tensor: \n {x} ")
print(f"\nTensor Shape: {x.shape} ")
print('-'*70,'\n')

#Reshape tensor
reshape_tensor=x.reshape(1,8)
print(f"Reshaped tensor: \n {reshape_tensor}\n ")
print(f"Reshaped tensor shape: \n {reshape_tensor.shape} ")

Original tensor: 
 tensor([[1, 2, 3, 5],
        [4, 5, 6, 9]]) 

Tensor Shape: torch.Size([2, 4]) 
---------------------------------------------------------------------- 

Reshaped tensor: 
 tensor([[1, 2, 3, 5, 4, 5, 6, 9]])
 
Reshaped tensor shape: 
 torch.Size([1, 8]) 


* **Transposing:** `torch.Tensor.transpose()` swaps the specified dimensions of a tensor.

In [9]:
x=torch.tensor([[1,2,3,5],[4,5,6,9]])
print(f"Original tensor: \n {x} ")
print(f"\nTensor Shape: {x.shape} ")
print('-'*70,'\n')

# Tranpose the tensor
transpose_tensor=x.transpose(0,1)
print(f"Tranposed tensor: {transpose_tensor} ")
print(f"Shape of transposed tensor: {transpose_tensor.shape} ")

Original tensor: 
 tensor([[1, 2, 3, 5],
        [4, 5, 6, 9]]) 

Tensor Shape: torch.Size([2, 4]) 
---------------------------------------------------------------------- 

Tranposed tensor: tensor([[1, 4],
        [2, 5],
        [3, 6],
        [5, 9]]) 
Shape of transposed tensor: torch.Size([4, 2]) 


### 2.4 - Combining Tensors

In the data preparation stage, you might need to combine data from different sources or merge separate batches into one larger dataset.

* `torch.cat()`: Joins a sequence of tensors along an existing dimension. Note: All tensors must have the same shape in dimensions other than the one being concatenated.

In [10]:
tensor_a = torch.tensor([[1, 2],
                         [3, 4]])
tensor_b = torch.tensor([[5, 6],
                         [7, 8]])

print(tensor_a,'\n\n', tensor_b,'\n','-'*70)
# Concatenate along row
row_concatenate=torch.cat((tensor_a,tensor_b),dim=0)
print(f"Tensor concatenated along row: \n {row_concatenate} \n Shape: {row_concatenate.shape}\n {'-'*70 }")

# Concatenate along column
column_concatenate=torch.cat((tensor_a,tensor_b),dim=1)
print(f"Tensor concatenated along column: \n {column_concatenate} \n Shape: {column_concatenate.shape} ")

tensor([[1, 2],
        [3, 4]]) 

 tensor([[5, 6],
        [7, 8]]) 
 ----------------------------------------------------------------------
Tensor concatenated along row: 
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]) 
 Shape: torch.Size([4, 2])
 ----------------------------------------------------------------------
Tensor concatenated along column: 
 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]]) 
 Shape: torch.Size([2, 4]) 


## 3 - Indexing & Slicing

After you have your data in a tensor, you will often need to access specific parts of it. Whether you are grabbing a single prediction to inspect its value, separating your input features from your labels, or selecting a subset of data for analysis, indexing and slicing are the tools for the job.

### 3.1 - Accessing Elements

These are the fundamental techniques for getting data out of a tensor, working very similarly to how you would access elements in a standard Python list.

* **Standard Indexing**: Accessing single elements or entire rows using integer indices (e.g., `x[0]`, `x[1, 2]`).

In [11]:
x = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(f"Original tensor: \n{x} ")
print('-'*70)

# Get one element
one_element=x[0,3]
print(f"Access one element: {one_element} ")
print('-'*70)

# Get entire row
entire_row=x[0,:]
print(f"Access entire first row: {entire_row} ")

# Get last row
last_row=x[-1,:]
print(f"Access last row: {last_row} ")
print('-'*70)

Original tensor: 
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]) 
----------------------------------------------------------------------
Access one element: 4 
----------------------------------------------------------------------
Access entire first row: tensor([1, 2, 3, 4]) 
Access last row: tensor([ 9, 10, 11, 12]) 
----------------------------------------------------------------------


<br>

* **Slicing**: Extracting sub-tensors using `[start:end:step]` notation (e.g., `x[:2, ::2]`).
    * *Note: The `end` index itself is not included in the slice.*
* Slicing can be used to access entire columns.

In [12]:
print(f"Original tensor: \n{x} ")
print('-'*70)

# First two rows
first_two_rows=x[0:2,:]
print(f"First two rows: \n {first_two_rows} ")
print('-'*70)

# third column of all row
third_column=x[:,2]
print(f"Third column : \n{third_column} ")
print('-'*70)

# Every other column
every_other_column=x[:,::2]
print(f"Every other column : \n {every_other_column} ")
print('-'*70)

# Last Column
last_column=x[:,-1]
print(f"Last column : \n {last_column} ")

Original tensor: 
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]) 
----------------------------------------------------------------------
First two rows: 
 tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]]) 
----------------------------------------------------------------------
Third column : 
tensor([ 3,  7, 11]) 
----------------------------------------------------------------------
Every other column : 
 tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11]]) 
----------------------------------------------------------------------
Last column : 
 tensor([ 4,  8, 12]) 


* Combining Indexing & Slicing

In [13]:
print(f"Original tensor: \n{x} ")
print('-'*70)

# first two rows and last two column
combined=x[0:2 ,2: ]
print(f"First two rows and last two column : \n {combined} ")


Original tensor: 
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]) 
----------------------------------------------------------------------
First two rows and last two column : 
 tensor([[3, 4],
        [7, 8]]) 


* **`.item()`**: Extracts the value from a single-element tensor as a standard Python number.

In [14]:
print(f"Original tensor: \n{x} ")
print('-'*70)

# Access one tensor value
one_element=x[1,0]
print(f'One element : {one_element} \nDatatype: {one_element.dtype} ')
print('-'*70)

# Convert tensor to python number
python_number=one_element.item()
print(f"Tensor is converted into python number {python_number}\nDatatype: {type(python_number)} ")

Original tensor: 
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]) 
----------------------------------------------------------------------
One element : 5 
Datatype: torch.int64 
----------------------------------------------------------------------
Tensor is converted into python number 5
Datatype: <class 'int'> 


### 3.2 - Advanced Indexing

For more complex data selection, such as filtering your dataset based on one or more conditions, you can use advanced indexing techniques.

* **Boolean Masking**: Using a boolean tensor to select elements that meet a certain condition (e.g., `x[x > 5]`).

In [15]:
print(f"Original tensor: \n{x} ")
print('-'*70)

# Create mask with value greater than 7
mask=x>7
print(f"Mask : \n{mask} ")
print('-'*70)

# Apply the mask 
mask_applied=x[mask]
print(f"Mask applied on tensor: \n{mask_applied} ")

Original tensor: 
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]) 
----------------------------------------------------------------------
Mask : 
tensor([[False, False, False, False],
        [False, False, False,  True],
        [ True,  True,  True,  True]]) 
----------------------------------------------------------------------
Mask applied on tensor: 
tensor([ 8,  9, 10, 11, 12]) 


## 4 - Mathematical & Logical Operations

At their core, neural networks are performing mathematical computations. A single neuron, for example, calculates a weighted sum of its inputs and adds a bias. PyTorch is optimized to perform these operations efficiently across entire tensors at once, which is what makes training so fast.

### 4.1 - Arithmetic

These operations are the foundation of how a neural network processes data. You'll see how PyTorch handles element-wise calculations and uses a powerful feature called broadcasting to simplify your code.

* **Element-wise Operations**: Standard math operators (`+`, `*`) that apply to each element independently.

In [16]:
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])
# Element wise addition
add=a+b
print(f"A: {a}\nB: {b}\nSum: {add} ")

# Element wise multiplication
multiply=a*b
print(f"Multiplication: {multiply} ")

A: tensor([1, 2, 3])
B: tensor([4, 5, 6])
Sum: tensor([5, 7, 9]) 
Multiplication: tensor([ 4, 10, 18]) 


* **Dot Product (`torch.matmul()`)**: Calculates the dot product of two vectors or matrices.

In [17]:
dot_product=torch.matmul(a,b)
print(f"A: {a}\nB: {b}\nDot product : {dot_product} ")

A: tensor([1, 2, 3])
B: tensor([4, 5, 6])
Dot product : 32 


<br>

* **Broadcasting**: The automatic expansion of smaller tensors to match the shape of larger tensors during arithmetic operations.
    * Broadcasting allows operations between tensors with compatible shapes, even if they don't have the exact same dimensions.

In [18]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([[1],
                 [2],
                 [3]])
print(f"Tensor A: \n{a}\nShape: {a.shape} \n\nTensor B:\n{b}\nShape: {b.shape}\n ")
print('-'*70)
broadcasting=a+b
print(f"Broadcasted the tensor : \n{broadcasting}\n Shape: {broadcasting.shape} ")
print('-'*70)

Tensor A: 
tensor([1, 2, 3])
Shape: torch.Size([3]) 

Tensor B:
tensor([[1],
        [2],
        [3]])
Shape: torch.Size([3, 1])
 
----------------------------------------------------------------------
Broadcasted the tensor : 
tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])
 Shape: torch.Size([3, 3]) 
----------------------------------------------------------------------


### 4.2 - Logic & Comparisons

Logical operations are powerful tools for data preparation and analysis. They allow you to create boolean masks to filter, select, or modify your data based on specific conditions you define.

* **Comparison Operators**: Element-wise comparisons (`>`, `==`, `<`) that produce a boolean tensor.

In [19]:
temperatures = torch.tensor([20, 35, 19, 35, 42])

# Tempereature greater than 30
is_hot=temperatures>30
print(f"Temperature greater than 30: {temperatures[is_hot]} ")

# Temperature less than equal to 20
is_cool=temperatures<=20
print(f"Tempearture less than equal to 20: {temperatures[is_cool]} ")

# Temperature exactly equal to 35
is_35_degree=(temperatures==35)
print(f"Temperature equal to 35: {is_35_degree} ")

Temperature greater than 30: tensor([35, 35, 42]) 
Tempearture less than equal to 20: tensor([20, 19]) 
Temperature equal to 35: tensor([False,  True, False,  True, False]) 


* **Logical Operators**: Element-wise logical operations (`&` for **AND**, `|` for **OR**) on boolean tensors.

In [20]:
is_morning = torch.tensor([True, False, False, True])
is_raining = torch.tensor([False, False, True, True])

print(f"is_morning: {is_morning}\nis_raining: {is_raining} ")
# Check if it is morning and raining
morning_and_raining= is_morning & is_raining

# Check if it is either morning or raining
morning_or_raining=is_morning | is_raining
print(f"\nMorning and Raining: {morning_and_raining}\nMorning or Raining: {morning_or_raining} ")

is_morning: tensor([ True, False, False,  True])
is_raining: tensor([False, False,  True,  True]) 

Morning and Raining: tensor([False, False, False,  True])
Morning or Raining: tensor([ True, False,  True,  True]) 


### 4.3 - Statistics

Calculating statistics like the mean or standard deviation can be useful for understanding your dataset or for implementing certain types of normalization during the data preparation phase.

* `torch.mean()`: Calculates the mean of all elements in a tensor.

In [21]:
data = torch.tensor([10.0, 20.0, 30.0, 40.0, 50.0])
print(data)

# Calculate mean
mean=data.mean()
print(f"Mean for the given dataset is {mean} ")

tensor([10., 20., 30., 40., 50.])
Mean for the given dataset is 30.0 


* `torch.std()`: Calculates the standard deviation of all elements.

In [22]:
data = torch.tensor([10.0, 20.0, 30.0, 40.0, 50.0])
print(data)

# Calculate Standard deviation
sd=data.std()
print(f"Standard deviation for given datapoint: {sd} ")

tensor([10., 20., 30., 40., 50.])
Standard deviation for given datapoint: 15.81138801574707 


### 4.4 - Data Types

Just as important as a tensor's shape is its data type. Neural networks typically perform their calculations using 32-bit floating point numbers (float32). Providing data of the wrong type, such as an integer, can lead to runtime errors or unexpected behavior during training. It is a good practice to ensure your tensors have the correct data type for your model.

* **Type Casting (`.int`, etc.)**: Converts a tensor from one data type to another (e.g., from float to integer).

In [23]:
data = torch.tensor([10.0, 20.0, 30.0, 40.0, 50.0])
print(f"Data is {data}\nDatatype: {data.dtype} ")

# Convert data to int
int_tensor=data.int()
print(f"\n\nCasted Data is {int_tensor}\nDatatype: {int_tensor.dtype} ")

Data is tensor([10., 20., 30., 40., 50.])
Datatype: torch.float32 


Casted Data is tensor([10, 20, 30, 40, 50], dtype=torch.int32)
Datatype: torch.int32 


## 5 - Optional Exercises


### Exercise 1: Analyzing Monthly Sales Data

You're a data analyst at an e-commerce company. You've been given a tensor representing the monthly sales of three different products over a period of four months. Your task is to extract meaningful insights from this data.

The tensor `sales_data` is structured as follows:

* **Rows** represent the **products** (Product A, Product B, Product C).

* **Columns** represent the **months** (Jan, Feb, Mar, Apr).

**Your goals are**:

1. Calculate the total sales for **Product B** (the second row).
2. Identify which months had sales **greater than 130** for **Product C** (the third row) using boolean masking.
3. Extract the sales data for all products for the months of **Feb and Mar** (the middle two columns).

<br>

<details>
<summary><span style="color:green;"><strong>Solution (Click here to expand)</strong></span></summary>

```python
### START CODE HERE ###

# 1. Calculate total sales for Product B.
total_sales_product_b = sales_data[1].sum()

# 2. Find months where sales for Product C were > 130.
high_sales_mask_product_c = sales_data[2] > 130

# 3. Get sales for Feb and Mar for all products.
sales_feb_mar = sales_data[:, 1:3]

### END CODE HERE ###
```

In [24]:
# Sales data for 3 products over 4 months
sales_data = torch.tensor([[100, 120, 130, 110],   # Product A
                           [ 90,  95, 105, 125],   # Product B
                           [140, 115, 120, 150]    # Product C
                          ], dtype=torch.float32)

print("ORIGINAL SALES DATA:\n\n", sales_data)
print("-" * 45)

# 1.Calculate the total sales for Product B (the second row).
sum_second_row=sum(sales_data[1,:])
print(f"Total sales for product B {sum_second_row}\n")
print("-" * 45)

# 2.Identify which months had sales greater than 130 for Product C (the third row) using boolean masking.
third_row=sales_data[2,:]
Mask=(third_row>130)
print(f"Months had sales greater than 130 {Mask}\n ")
print("-" * 45)

# 3. Extract the sales data for all products for the months of Feb and Mar  (the middle two columns).
middle_column=sales_data[:,1:3]
print(f" Sales data for all the product ofr Feb and Mar: \n {middle_column} ")

ORIGINAL SALES DATA:

 tensor([[100., 120., 130., 110.],
        [ 90.,  95., 105., 125.],
        [140., 115., 120., 150.]])
---------------------------------------------
Total sales for product B 415.0

---------------------------------------------
Months had sales greater than 130 tensor([ True, False, False,  True])
 
---------------------------------------------
 Sales data for all the product ofr Feb and Mar: 
 tensor([[120., 130.],
        [ 95., 105.],
        [115., 120.]]) 


### Exercise 2: Image Batch Transformation

You're working on a computer vision model and have a batch of 4 grayscale images, each with a size of 3 pixels high by 2 pixels wide. The data is currently in a tensor with the shape `[4, 3, 2]`, which represents `[batch_size, height, width]`.

For processing with certain deep learning frameworks, you need to transform this data into the `[batch_size, channels, height, width]` format. Since the images are grayscale, **you'll need to**:

1. Add a new dimension of size 1 at index 1 to represent the color channel.
2. After adding the channel, you realize the model expects the shape `[batch_size, height, width, channels]`. Transpose the tensor to move the channel dimension to the last position without scrambling the height and width. Use `.transpose()` multiple times.

<br>

<details>
<summary><span style="color:green;"><strong>Solution (Click here to expand)</strong></span></summary>

```python
### START CODE HERE ###

# 1. Add a channel dimension at index 1.
# Result: [batch, channels, height, width]
image_batch_with_channel = image_batch.unsqueeze(1)

# 2. Transpose to get [batch, height, width, channels].
# Step A: Swap channels (1) with height (2)
# Result: [batch, height, channels, width]
temp_tensor = image_batch_with_channel.transpose(1, 2)

# Step B: Swap channels (2) with width (3)
# Result: [batch, height, width, channels]
image_batch_transposed = temp_tensor.transpose(2, 3)

### END CODE HERE ###
```

In [25]:
# A batch of 4 grayscale images, each 3x2
image_batch=torch.rand(4,3,2)
print(f"Original batch shape: {image_batch.shape} ")

# 1. Add a new dimension of size 1 at index 1 to represent the color channel.
expanded=image_batch.unsqueeze(1)
print(f"New dimension of size 1 added to represent color channel : {expanded.shape} ")

# 2. Make channel dimension to last position
#swap channel and width
swap1=expanded.transpose(1,3)
print(swap1.shape)
#swap width and height
swap2=swap1.transpose(1,2)
print(swap2.shape)

print(f"Dimension in this format [batch_size, height, width, channels] {swap2.shape} ")

Original batch shape: torch.Size([4, 3, 2]) 
New dimension of size 1 added to represent color channel : torch.Size([4, 1, 3, 2]) 
torch.Size([4, 2, 3, 1])
torch.Size([4, 3, 2, 1])
Dimension in this format [batch_size, height, width, channels] torch.Size([4, 3, 2, 1]) 


### Exercise 3: Combining and Weighting Sensor Data

You're building an environment monitoring system that uses two sensors: one for temperature and one for humidity. You receive data from these sensors as two separate 1D tensors.

**Your task is to**:

1. **Concatenate** the two tensors into a single `2x5` tensor, where the first row is temperature data and the second is humidity data.
2. Create a `weights` tensor `torch.tensor([0.6, 0.4])`.
3. Use **broadcasting and element-wise multiplication** to apply these weights to the combined sensor data. The temperature data should be multiplied by 0.6 and the humidity data by 0.4.
4. Finally, calculate the **weighted average** for each time step by **summing** the weighted values along `dim=0` and **dividing** by the sum of the weights.

<br>

<details>
<summary><span style="color:green;"><strong>Solution (Click here to expand)</strong></span></summary>

```python
### START CODE HERE ###

# 1. Concatenate the two tensors.
# Note: You need to unsqueeze them first to stack them vertically.
combined_data = torch.cat((temperature.unsqueeze(0), humidity.unsqueeze(0)), dim=0)

# 2. Create the weights tensor.
weights = torch.tensor([0.6, 0.4])

# 3. Apply weights using broadcasting.
# You need to reshape weights to [2, 1] to broadcast across columns.
weighted_data = combined_data * weights.unsqueeze(1)

# 4. Calculate the weighted average for each time step.
#    (A true average = weighted sum / sum of weights)
weighted_sum = torch.sum(weighted_data, dim=0)
weighted_average = weighted_sum / torch.sum(weights)

### END CODE HERE ###
```

In [26]:
# Sensor readings (5 time steps)
temperature = torch.tensor([22.5, 23.1, 21.9, 22.8, 23.5])
humidity = torch.tensor([55.2, 56.4, 54.8, 57.1, 56.8])

# 1. Concatenate the two tensors into a single 2x5 tensor, where the first row is temperature data and the second is humidity data.
# unsqueeze so that we can concatenate
temperature_unsqueeze=temperature.unsqueeze(0)
humidity_unsqueeze=humidity.unsqueeze(0)
combine_data=torch.cat((temperature_unsqueeze,humidity_unsqueeze),dim=0)
print(f"Concatenate two tensor:\n {combine_data} ")
print('-'*70)

# 2. Create a weights tensor torch.tensor([0.6, 0.4]).
weight=torch.tensor([0.6,0.4])


# 3. Use broadcasting and element-wise multiplication to apply these weights to the combined sensor data.
# make weight as two dimension so that broadcasting can happen - Both should be in same dimension
weight=weight.unsqueeze(1)
print(f"Weight shape: {weight.shape}\nCombined Data shape:{combine_data.shape} \n" )
element_wise_multiplication=weight*combine_data
print(f"element-wise multiplication on weight and combine data \n {element_wise_multiplication} ")
print('-'*70)

# 4. Finally, calculate the weighted average for each time step by summing the weighted values along dim=0 and dividing by the sum of the weights.
weighted_sum=element_wise_multiplication.sum(dim=0)
weighted_sum_average=weighted_sum/(weight.sum(dim=0))
print(f"Weighted average sum {weighted_sum_average} ")

Concatenate two tensor:
 tensor([[22.5000, 23.1000, 21.9000, 22.8000, 23.5000],
        [55.2000, 56.4000, 54.8000, 57.1000, 56.8000]]) 
----------------------------------------------------------------------
Weight shape: torch.Size([2, 1])
Combined Data shape:torch.Size([2, 5]) 

element-wise multiplication on weight and combine data 
 tensor([[13.5000, 13.8600, 13.1400, 13.6800, 14.1000],
        [22.0800, 22.5600, 21.9200, 22.8400, 22.7200]]) 
----------------------------------------------------------------------
Weighted average sum tensor([35.5800, 36.4200, 35.0600, 36.5200, 36.8200]) 


### Exercise 4: Feature Engineering for Taxi Fares

You are working with a dataset of taxi trips. You have a tensor, `trip_data`, where each row is a trip and the columns represent **[distance (km), hour_of_day (24h)]**.

**Your goal** is to engineer a new binary feature called `is_rush_hour_long_trip`. This feature should be `True` (or `1`) only if a trip meets **both** of the following criteria:

* It's a **long trip** (distance > 10 km).
* It occurs during a **rush hour** (8-10 AM or 5-7 PM, i.e., `[8, 10)` or `[17, 19)`).

To achieve this, you will need to:

1. **Slice** the `trip_data` tensor to isolate the `distance` and `hour` columns.
2. Use **logical and comparison operators** to create boolean masks for each condition (long trip, morning rush, evening rush).
3. Combine these masks to create the final `is_rush_hour_long_trip` feature.
4. **Reshape** this new 1D feature tensor into a 2D column vector and convert its data type to float so it can be combined with the original data.

<br>

<details>
<summary><span style="color:green;"><strong>Solution (Click here to expand)</strong></span></summary>

```python
### START CODE HERE ###

# 1. Slice the main tensor to get 1D tensors for each feature.
distances = trip_data[:, 0]
hours = trip_data[:, 1]

# 2. Create boolean masks for each condition.
is_long_trip = distances > 10.0
is_morning_rush = (hours >= 8.0) & (hours < 10.0)
is_evening_rush = (hours >= 17.0) & (hours < 19.0)

# 3. Combine masks to identify rush hour long trips.
# A trip is a rush hour long trip if it's (a morning OR evening rush) AND a long trip.
is_rush_hour_long_trip_mask = (is_morning_rush | is_evening_rush) & is_long_trip

# 4. Reshape the new feature into a column vector and cast to float.
new_feature_col = is_rush_hour_long_trip_mask.float().unsqueeze(1)

### END CODE HERE ###
```

In [51]:
# Data for 8 taxi trips: [distance, hour_of_day]
trip_data = torch.tensor([
    [5.3, 7],   # Not rush hour, not long
    [12.1, 9],  # Morning rush, long trip -> RUSH HOUR LONG
    [15.5, 13], # Not rush hour, long trip
    [6.7, 18],  # Evening rush, not long
    [2.4, 20],  # Not rush hour, not long
    [11.8, 17], # Evening rush, long trip -> RUSH HOUR LONG
    [9.0, 9],   # Morning rush, not long
    [14.2, 8]   # Morning rush, long trip -> RUSH HOUR LONG
], dtype=torch.float32)


print("ORIGINAL TRIP DATA (Distance, Hour):\n\n", trip_data)
print("-" * 55)

# 1. Slice the trip_data tensor to isolate the distance and hour columns.
Distance=trip_data[:,0]
Hour=trip_data[:,1]
print(f"Distance : {Distance} \nHour: {Hour} ")

# 2. Use logical and comparison operators to create boolean masks for each condition (long trip, morning rush, evening rush)

# time is converted into int for comparision
time_int_datatype=Hour.int()

# Mask for distance and time
distance_mask=Distance>10
time_mask=((time_int_datatype>=8) & (time_int_datatype<10)) | ((time_int_datatype>=17) & (time_int_datatype<19))

print(f"\nDistance mask : {distance_mask}\nTime Mask: {time_mask} ")

# Combine these masks to create the final is_rush_hour_long_trip feature.
is_rush_hour_long_trip_mask_combine=torch.cat((distance_mask.squeeze(0),time_mask.squeeze(0)),dim=0)
print(f"\nCombined mask : \n{is_rush_hour_long_trip_mask_combine} ")

# Reshape the mask 
is_rush_hour_long_trip_mask_combine.reshape(8,2)

ORIGINAL TRIP DATA (Distance, Hour):

 tensor([[ 5.3000,  7.0000],
        [12.1000,  9.0000],
        [15.5000, 13.0000],
        [ 6.7000, 18.0000],
        [ 2.4000, 20.0000],
        [11.8000, 17.0000],
        [ 9.0000,  9.0000],
        [14.2000,  8.0000]])
-------------------------------------------------------
Distance : tensor([ 5.3000, 12.1000, 15.5000,  6.7000,  2.4000, 11.8000,  9.0000, 14.2000]) 
Hour: tensor([ 7.,  9., 13., 18., 20., 17.,  9.,  8.]) 

Distance mask : tensor([False,  True,  True, False, False,  True, False,  True])
Time Mask: tensor([False,  True, False,  True, False,  True,  True,  True]) 

Combined mask : 
tensor([False,  True,  True, False, False,  True, False,  True, False,  True,
        False,  True, False,  True,  True,  True]) 


torch.Size([16])

In [52]:
is_rush_hour_long_trip_mask_combine.reshape(8,2)

tensor([[False,  True],
        [ True, False],
        [False,  True],
        [False,  True],
        [False,  True],
        [False,  True],
        [False,  True],
        [ True,  True]])

In [30]:
print(Distance)

tensor([ 5.3000, 12.1000, 15.5000,  6.7000,  2.4000, 11.8000,  9.0000, 14.2000])



Distance mask : tensor([False,  True,  True, False, False,  True, False,  True])
Time Mask: tensor([False,  True, False,  True, False,  True,  True,  True]) 
